{% set name = "snpkit" %}
{% set version = "Beta2.0.1" %}
{% set sha256 = "98e449e6d6e294c4205dca25db4415b87dbd68b9a833c4f13f199081a68e81b6" %}
{% set user = "alipirani88" %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  url: 'https://github.com/{{ user }}/{{ name }}/archive/v{{ version }}.tar.gz'
  sha256: '{{ sha256 }}'

build:
  number: 0
  noarch: generic

requirements:
  host:
    - python >=3.6
    - pip
    - pysam >=0.15.2
  run:
    - python >=3.6
    - pysam >=0.15.2
test:
  commands:
    - snpkit -h

about:
  home: 'https://github.com/{{ user }}/{{ name }}'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modular workflow for Microbial Variant Calling and SNP diagnostics.
